version: '3.8'

services:

  rabbitmq:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservices-network
    environment:
      RABBITMQ_DEFAULT_USER: "username"
      RABBITMQ_DEFAULT_PASS: "password"

  
  estoque:
    build:
      context: ./estoque
    ports:
      - "3002:3002"
    networks:
      - microservices-network
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=username
      - RABBITMQ_PASS=password

  vendas:
    build:
      context: ./vendas
    ports:
      - "3001:3001"
    networks:
      - microservices-network
    depends_on:
      - rabbitmq
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=username
      - RABBITMQ_PASS=password


networks:
  microservices-network:
    driver: bridge
